version: '3.8'
services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    image: final_2020038040:v1
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
